In [2]:
import numpy as np

In [6]:
my_list = [1,2,3]

In [7]:
arr = np.array(my_list)

In [8]:
arr

array([1, 2, 3])

In [9]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.linspace(0, 5, 20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(5)

array([0.66304181, 0.65444976, 0.38272062, 0.88979398, 0.97176389])

In [19]:
np.random.rand(5,5)

array([[0.77810828, 0.8737974 , 0.32515719, 0.57571484, 0.07832075],
       [0.5220319 , 0.02313116, 0.958385  , 0.78365227, 0.24722643],
       [0.50697869, 0.90661309, 0.6938739 , 0.45484729, 0.91258394],
       [0.86676628, 0.06072098, 0.91933741, 0.18842624, 0.35824021],
       [0.33531453, 0.7364202 , 0.99883976, 0.03018706, 0.72025992]])

In [20]:
np.random.randn(5) #normal distribution

array([-0.08555122,  1.48911181,  0.75419954, -0.58860151, -1.11208197])

In [21]:
np.random.randn(5,5)

array([[-0.28403308,  1.59325107, -0.75048599,  0.58447437,  0.97641366],
       [-0.40144758, -0.82272836, -0.59622657,  1.08489768, -1.20576001],
       [-1.08581433, -1.11458623, -0.95058952, -0.62065108, -1.36245035],
       [ 2.53263723, -0.17335942, -1.31807385,  0.46820781,  1.0971149 ],
       [-1.4557111 , -0.57784497,  0.48903448,  0.32908494, -0.98361634]])

In [22]:
np.random.randint(1,100)

75

In [23]:
np.random.randint(1,100,10)

array([83, 36, 24, 24, 90, 25, 66, 88, 11, 68])

In [27]:
arr = np.arange(25)

In [31]:
rarr = np.random.randint(1,50,10)
rarr

array([36, 12, 25, 16, 16, 15, 38, 30, 19, 48])

In [26]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
rarr.max()

48

In [33]:
rarr.min()

12

In [34]:
rarr.argmax() #index of max value

9

In [35]:
rarr.argmin() #index of min value

1

In [36]:
arr.shape

(25,)

In [38]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [45]:
arr = np.arange(0,11)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr[8]

8

In [42]:
arr[1:5]

array([1, 2, 3, 4])

In [47]:
slice_arr = arr[:5] #shallow copy
slice_arr

array([0, 1, 2, 3, 4])

In [48]:
print(arr)
slice_arr[:] = 99
print(slice_arr)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[99 99 99 99 99]
[99 99 99 99 99  5  6  7  8  9 10]


In [49]:
arr_copy = arr.copy() #deep copy
print(arr)
print(arr_copy)
arr_copy[:] = 88
print(arr)
print(arr_copy)

[99 99 99 99 99  5  6  7  8  9 10]
[99 99 99 99 99  5  6  7  8  9 10]
[99 99 99 99 99  5  6  7  8  9 10]
[88 88 88 88 88 88 88 88 88 88 88]


In [50]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [51]:
arr_2d[0][0]

5

In [52]:
arr_2d[0]

array([ 5, 10, 15])

In [53]:
arr_2d[0,0]

5

In [54]:
print(arr_2d[1][1])
print(arr_2d[1,1])

25
25


In [56]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [57]:
arr = np.arange(1,11)

In [59]:
bool_arr = arr > 5 #conditional selection
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [60]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [61]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [63]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [64]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [65]:
arr*arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [66]:
arr/arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [67]:
arr + 100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [69]:
arr = np.arange(0,11)
arr/arr

/home/canaybozkus/.local/lib/python2.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in divide
  


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [70]:
arr / 0

/home/canaybozkus/.local/lib/python2.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in divide
  """Entry point for launching an IPython kernel.


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [71]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [72]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [74]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [75]:
np.log(arr)

/home/canaybozkus/.local/lib/python2.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

# Exercises

In [76]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [77]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [78]:
np.random.randint(5,6,10) #-> np.ones(10) * 5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [79]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [80]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [81]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [82]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [83]:
np.random.rand()

0.3833169000457244

In [84]:
np.random.randn(25)

array([ 2.7735003 , -0.02878238, -0.71557912, -1.84474689, -0.67598406,
       -0.65561414,  1.17973261, -0.44397815, -0.13788221,  0.18771119,
       -0.04557392, -0.1895062 ,  0.73441624, -0.63899343, -0.12974477,
        0.2394226 ,  0.65597363,  0.2606882 ,  1.35524181, -0.50574222,
       -0.97061137,  1.31206045,  0.47333251,  0.88444338,  0.23473097])

In [88]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [89]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [90]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [91]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [94]:
mat[3,4]

20

In [100]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [101]:
mat[4]

array([21, 22, 23, 24, 25])

In [102]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [103]:
mat.sum()

325

In [105]:
mat.std() #np.std(mat)

7.211102550927978

In [106]:
mat.sum(0)

array([55, 60, 65, 70, 75])